sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mmadi/docker-react -f Dockerfile.dev .

script:
  - - docker run -e CI=true mmadi/docker-react npm run test
